# stages:
#   - DeployDev
# cache:
#   paths:
#     - node_modules/
# DeployDev:
#   stage: DeployDev
#   image: node:16.16.0
#   only: ["develop"]
#   script:
#     - apt-get update && apt-get install rsync -y && apt-get install openssh-server -y
#     - mkdir -p ~/.ssh
#     - ssh-keyscan -H "$SERVER_IP" >> ~/.ssh/known_hosts
#     - echo "$SSH_KEY_DEV" > ~/.ssh/id_rsa
#     - chmod 600 ~/.ssh/id_rsa
#     - echo "$ENV_DEV" > .env
#     - yarn install
#     - CI= && yarn run build
#     - rsync --progress -avzh -e "ssh -i ~/.ssh/id_rsa" --rsync-path="sudo rsync" --exclude={.git,node_modules} . $SERVER_NAME@$SERVER_IP:/var/www/html/recruit-cms
