export const USER_INFO = "USER_INFO";
export const USE_GET_LIST_CANDIDATE = "USE_GET_LIST_CANDIDATE";
export const USE_GET_LIST_JOB = "USE_GET_LIST_JOB";
export const USE_GET_DETAIL_JOB = "USE_GET_DETAIL_JOB";
export const USE_GET_LIST_CANDIDATE_AVAILABLE =
  "USE_GET_LIST_CANDIDATE_AVAILABLE";
export const USE_GET_LIST_ORDER = "USE_GET_LIST_ORDER";
export const USE_GET_DETAIL_ORDER = "USE_GET_DETAIL_ORDER";
export const USE_GET_LIST_ORDER_AVAILABLE = "USE_GET_LIST_ORDER_AVAILABLE";

export const GET_LIST_POSITION = "GET_LIST_POSITION";
export const GET_LIST_SKILL = "GET_LIST_SKILL";
export const GET_LIST_LEVEL = "GET_LIST_LEVEL";
export const GET_LIST_SCHOOL = "GET_LIST_SCHOOL";
export const GET_LIST_EXPERIENCE = "GET_LIST_EXPERIENCE";
export const GET_LIST_PERSONNEL_TYPE = "GET_LIST_PERSONNEL_TYPE";
export const GET_LIST_CONTRACT_TYPE = "GET_LIST_CONTRACT_TYPE";
